version: "3.7"

services:
  app:
    build: .
    image: docker-registry.i.mm12.xyz/scouting-app:latest
    env_file: .env
    environment:
      - MONGO_URL=mongodb://db:27017
    ports:
      - 8080:8080
    platform: linux/x86-64
  db:
    image: mongo:4.4
    volumes:
      - db-data:/data/db
    command: "mongod --replSet rs0"
    ports:
      - 27017:27017

volumes:
  db-data:
